config/routes.rb
Rails.application.routes.draw do

	root 'pages#index'
	get 'kvantums/index'
	get 'about', to: 'pages#about'

	resources :enrollments, only: [:new, :create, :destroy]
	resources :students
	resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	validates :user_id, presence: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
	belong_to :student
	belong_to :kvantum
end

app/models/kvantum.rb
class Kvantum < ApplicationRecord
	has_many :enrollments
	has_many :students, through: :enrollments
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :enrollments
	has_many :kvantums, through: :enrollments
	validates :name, presence: true
	validates :name, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	# 
	has_many :articles
	has_secure_password
	validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, 
	format: { with: VALID_EMAIL_REGEX }
	before_save { self.email = email.downcase }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user, :logged_in?
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	def logged_in?
		!!current_user
	end
	def require_user
		if !logged_in?
			flash[:danger] = "Вы должны войти в систему, чтобы выполнить это действие"
			redirect_to root_path
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	before_action :set_article, only: [:edit, :update, :show, :destroy]

	def new
		# Создаем статью
		@article = Article.new
	end

	def create
		#render plain: params[:article].inspect
		@article = Article.new(article_params)
		@article.user = User.first
		if @article.save
			flash[:notice] = "Статья успешно создана"
			redirect_to articles_path(@article)
		else
			render 'new'
		end
	end

	def show
		@article = Article.find(params[:id])
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			flash[:notice] = "Статья успешно обновлена"
			redirect_to article_path(@article)
		else
			flash[:notice] = "Статья не обновлена!"
			render 'edit'
		end
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy
		flash[:notice] = "Статья успешно удалена"
		redirect_to articles_path
	end

	def set_article
		@article = Article.find(params[:id])
	end

	private
	def article_params
		params.require(:article).permit(:title, :description)
	end
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  def index
  end

  def new
  	@enrollment = Enrollment.new
  end

  def create
  	@enrollment = Enrollment.create(params.require(:enrollment).permit(:kvantum_id, :student_id))
  	redirect_to student_path(@enrollment.student)
  end

  def destroy
  	@enrollment = Enrollment.find(params[:id])
  	@student = @enrollment.student
  	@enrollment.destroy
  	redirect_to student_path(@student)
  end
end

app/controllers/kvantums_controller.rb
class KvantumsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end

	def about
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    @student = Student.create(params.require(:student).permit(:organization, :inputsCertificate))
    if @student.valid?
      redirect_to student_path
    else
      flash[:errors] = @student.errors.full_messages
      redirect_to new_student_path
    end
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    @student = Student.find(params[:id])
    @student.update(params.require(:student).permit(:organization, :inputsCertificate))
    redirect_to student_path(@student)
  end

  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to student_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/kvantums_helper.rb
module KvantumsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
	<div class="col-xs-12">
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :title %>
			</div>
			<div class="col-sm-6">
				<%= f.text_field :title, class: "form-control", placeholder: "Название статьи", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :description %>
			</div>
			<div class="col-sm-6">
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Текст статьи" %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="button" class="btn btn-default"><%= link_to 'Назад', articles_path %></button>
				<%= f.submit 'Создать статью', class: 'btn btn-primary btn-large' %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/articles/edit.html.erb
<h1>Редактирование статьи</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Вывод всех статей</h1>
<% @articles.each do |article| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="well well-lg">
    <div class="article-title">
     <%= link_to article.title, article_path(article) %>
   </div>
   <div class="article-body">
     <%= truncate(article.description, length: 100) %>
   </div>

   <div class="article-meta-details">
    <small>Создано: <%= article.user.username if article.user %>, <%= time_ago_in_words(article.created_at) %> ago, последнее обновление: <%= time_ago_in_words(article.updated_at) %> ago</small>
   </div>

    <div class="article-actions">
     <%= link_to "Редактировать", edit_article_path(article), class: "btn btn-xs btn-primary" %>
     <%= link_to "Удалить", article_path(article), method: :delete, data: { confirm: "Вы действительно хотите удалить статью?"}, class: "btn btn-xs btn-danger" %>
   </div>
 </div>
</div>
</div>
<% end %>

app/views/articles/new.html.erb
<% if @article.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(@article.errors.count, "error") %>
      prohibited this article from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% @article.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
 <% if @article.user %>
 <ul class="listing">
  <div class="row" align="center">
   <div class="col-md-4 col-md-offset-4">
    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
    <li class="article-title"><%= link_to @article.user.username, user_path(@article.user) %></li>
    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></small></li>
   </div>
  </div>
 </ul> 
 <% end %>
 <h4 class="center description"><strong>Description:</strong></h4>
 <hr>
 <%= simple_format(@article.description) %>
 <div class="article-actions">
 <%= link_to "Edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
 <%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
 <%= link_to "Back", articles_path, class: "btn btn-xs btn-success" %>
 </div>
</div>

app/views/enrollments/create.html.erb
<h1>Enrollments#create</h1>
<p>Find me in app/views/enrollments/create.html.erb</p>

app/views/enrollments/destroy.html.erb
<h1>Enrollments#destroy</h1>
<p>Find me in app/views/enrollments/destroy.html.erb</p>

app/views/enrollments/index.html.erb
<h1>Enrollments#index</h1>
<p>Find me in app/views/enrollments/index.html.erb</p>

app/views/enrollments/new.html.erb
<h1>Добавить квантум</h1>

<%= form_for @enrollment do |f| %>
	<%= f.label :kvantum_id %>
	<%= f.collection_select :kvantum_id, Kvantum.all, :id, :name %>
	<%= f.label :student_id %>
	<%= f.collection_select :student_id, Student.all, :id, :name %>
<% end %>

app/views/enrollments/show.html.erb
<h1>Добавить квантум</h1>

<%= form_for @enrollment do |f| %>
	<%= f.label :kvantums_id %>
	<%= f.collection_select :kvantums_id, Kvantum.all, :id, :name %>
	<%= f.label :student_id %>
	<%= f.collection_select :student_id, Student.all, :id, :name %>
<% end %>

app/views/kvantums/index.html.erb
<h1>Kvantums#index</h1>
<p>Find me in app/views/kvantums/index.html.erb</p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Brand</a> -->
      <%= link_to "CTT-MKI System", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><li><%= link_to "Статьи", articles_path %></li>
        <li><%= link_to "Создать статью", new_article_path %></li>
        <li><%= link_to "Студенты", students_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "Войти", login_path, method: :login %></li>
        <% else %>
        <li><%= link_to "Выйти", logout_path, method: :delete %></li>
        <% end %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cttmki</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This About pages</h1>

app/views/pages/index.html.erb
<h1>Hello! This index pages</h1>
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>

app/views/shared/_article.html.erb
<% obj.each do |article| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to article.title, article_path(article) %>
        </div>
        <div class="article-body">
          <%= truncate(article.description, length: 100) %>
          <div class="article-meta-details">
          <small>Created by: <%= article.user.username if article.user %>,
                    <%= time_ago_in_words(article.created_at) %> ago,
                    last updated: <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
        <div class="article-actions">
          <%= link_to "Edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete", article_path(article), method: :delete, data: { confirm: "Are you sure you want to delete this article?"}, class: "btn btn-xs btn-danger" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
 <div class="row">
  <div class="col-xs-8 col-xs-offset-2">
   <div class="panel panel-danger">
    <div class="panel-heading">
     <h2 class="panel-title">
      <%= pluralize(obj.errors.count, "error") %>
      prohibited this object from being saved:
     </h2>
     <div class="panel-body">
      <ul>
       <% obj.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
       <% end %>
      </ul>
     </div>
    </div>
   </div>
  </div>
 </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/students/create.html.erb
<h1>Students#create</h1>
<p>Find me in app/views/students/create.html.erb</p>

app/views/students/destroy.html.erb
<h1>Students#destroy</h1>
<p>Find me in app/views/students/destroy.html.erb</p>

app/views/students/edit.html.erb
<h1>Students#edit</h1>
<p>Find me in app/views/students/edit.html.erb</p>

app/views/students/index.html.erb
<h1>Студент </h1>
<%= button_to "Добавить нового студента", new_student_path, method: :get %>
<ul>
	<% @students.each do |student| %>
	<li><%= link_to student.inputsCertificate, student_path(student) %></li>
	<% end %>
</ul>

app/views/students/new.html.erb
<div class="row">
	<div class="col-xs-12">
		<%= form_for(@student, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :organization %>
			</div>
			<div class="col-sm-6">
				<%= f.text_field :organization, class: "form-control", placeholder: "Название организации", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :inputsCertificate %>
			</div>
			<div class="col-sm-6">
				<%= f.text_field :inputsCertificate, rows: 10, class: "form-control", placeholder: "Введите номер сертификата" %>
			</div>
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit 'Добавить студента', class: 'btn btn-primary btn-large' %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/students/show.html.erb
<h1><%= @student.inputsCertificate %> страница</h1>

<h2>Возраст: <%= @student.organization %></h2>

<%= button_to "Добавить в квантум", new_enrollment_path, method: :get %>
<ul>
	<% @student.enrollments.each do |enrollment|%>
		<li><% enrollment.kvantoriums.inputsCertificate %></li>
		<%= button_to "Добавить квантум", enrollment_path(enrollment), method: :delete %>
	<% end %>
</ul>

<%= button_to "Редактировать студента", edit_student_path, method: :get %>
<%= button_to "Удалить студента", student_path, method: :delete %>

<%= link_to "Удалить студента", student_path %>

app/views/students/update.html.erb
<h1>Students#update</h1>
<p>Find me in app/views/students/update.html.erb</p>